package com.example.dlmsconfigurator.core.dlms

fun resolveDlmsUnit(unitCode: Int): String = when (unitCode) {
    0 -> "none"
    1 -> "year"
    2 -> "month"
    3 -> "week"
    4 -> "day"
    5 -> "hour"
    6 -> "minute"
    7 -> "second"
    8 -> "degree"
    9 -> "degree Celsius"
    10 -> "currency"
    11 -> "metre"
    12 -> "metre per second"
    13 -> "cubic metre"
    14 -> "cubic metre corrected"
    15 -> "cubic metre per hour"
    16 -> "cubic metre per hour corrected"
    17 -> "cubic metre per day"
    18 -> "cubic metre per day corrected"
    19 -> "litre"
    20 -> "kilogram"
    21 -> "newton"
    22 -> "newton metre"
    23 -> "pascal"
    24 -> "bar"
    25 -> "joule"
    26 -> "joule per hour"
    27 -> "watt"
    28 -> "volt ampere"
    29 -> "var"
    30 -> "watt hour"
    31 -> "volt ampere hour"
    32 -> "var hour"
    33 -> "ampere"
    34 -> "coulomb"
    35 -> "volt"
    36 -> "volt per metre"
    37 -> "farad"
    38 -> "ohm"
    39 -> "ohm metre"
    40 -> "weber"
    41 -> "tesla"
    42 -> "ampere per metre"
    43 -> "henry"
    44 -> "hertz"
    45 -> "active energy meter constant"
    46 -> "reactive energy meter constant"
    47 -> "apparent energy meter constant"
    48 -> "volt squared hour"
    49 -> "ampere squared hour"
    50 -> "kilogram per second"
    51 -> "siemens"
    52 -> "kelvin"
    53 -> "volt squared hour meter constant"
    54 -> "ampere squared hour meter constant"
    55 -> "volt ampere hour meter constant"
    56 -> "percentage"
    57 -> "ampere hour"
    60 -> "watt hour per cubic metre"
    61 -> "joule per cubic metre"
    62 -> "mole percent"
    63 -> "gram per cubic metre"
    64 -> "pascal second"
    255 -> "other"
    else -> "unit $unitCode"
}

fun preferredIndianUnitName(unitName: String): String = when (unitName) {
    "watt hour" -> "Wh"
    "volt ampere hour" -> "VAh"
    "var hour" -> "varh"
    "watt" -> "W"
    "volt ampere" -> "VA"
    "var" -> "var"
    "ampere" -> "A"
    "volt" -> "V"
    "hertz" -> "Hz"
    "percentage" -> "%"
    else -> unitName
}
